apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudcampus-backend-db
  namespace: cloudcampus
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: cloudcampus-backend-db
    creationPolicy: Owner

  data:
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: rds!db-19fd8ef0-6026-4ca5-8093-1458ba14af93
        property: username

    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: rds!db-19fd8ef0-6026-4ca5-8093-1458ba14af93
        property: password
