clusterName: dev-eks-cluster
region: us-west-2
vpcId: vpc-0140af903a199a8c3
serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::938379788459:role/dev-alb-controller-role

defaultTargetType: ip
