apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudcampus-backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    repoURL: https://github.com/pagotiramarao/cloudcampus-platform-gitops.git
    targetRevision: main
    path: helm/backend

    helm:
      releaseName: cloudcampus-backend

  destination:
    server: https://kubernetes.default.svc
    namespace: cloudcampus

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
