replicaCount: 2

image:
  repository: 938379788459.dkr.ecr.us-west-2.amazonaws.com/dev-backend
  tag: "15-8bc6864"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

database:
  host: dev-cloudcampus-postgres.cvw2qqgkq5yb.us-west-2.rds.amazonaws.com
  port: 5432
  name: cloudcampus

secret:
  name: cloudcampus-backend-db

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

probes:
  readiness:
    path: /actuator/health
    initialDelaySeconds: 15
    periodSeconds: 10

  liveness:
    path: /actuator/health
    initialDelaySeconds: 30
    periodSeconds: 20

ingress:
  enabled: true
  className: alb
  host: api.mybanking.shop

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-west-2:938379788459:certificate/d35ebdde-dbbf-4b45-96c0-fcba72f11fbe"
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
