replicaCount: 2

image:
  repository: 938379788459.dkr.ecr.us-west-2.amazonaws.com/dev-backend
  tag: "13-db49121"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

database:
  host: dev-cloudcampus-postgres.cvw2qqgkq5yb.us-west-2.rds.amazonaws.com
  port: 5432
  name: cloudcampus

secret:
  name: cloudcampus-backend-db

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

probes:
  readiness:
    path: /actuator/health
    initialDelaySeconds: 15
    periodSeconds: 10

  liveness:
    path: /actuator/health
    initialDelaySeconds: 30
    periodSeconds: 20
