replicaCount: 2

image:
  repository: 938379788459.dkr.ecr.us-west-2.amazonaws.com/dev-frontend
  tag: "15-8bc6864"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

containerPort: 80

health:
  path: /

ingress:
  enabled: true
  scheme: internet-facing
  targetType: ip
  healthcheckPath: /
  host: mybanking.shop
  certificateArn: "arn:aws:acm:us-west-2:938379788459:certificate/d35ebdde-dbbf-4b45-96c0-fcba72f11fbe"
