replicaCount: 2

image:
  repository: 250224372179.dkr.ecr.us-west-2.amazonaws.com/dev-frontend
  tag: "7-bb3e08c"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

containerPort: 80

health:
  path: /

ingress:
  enabled: true
  scheme: internet-facing
  targetType: ip
  healthcheckPath: /
  host: mybanking.shop
  certificateArn: "arn:aws:acm:us-west-2:250224372179:certificate/9fecdede-c86a-46ec-a7b2-dbf549eee0db"
